services:
  minio:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    ports:
      - "127.0.0.1:9000:9000" # minio api
      - "127.0.0.1:9080:9080" # minio console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_CONSOLE_ADDRESS=:9080
      - MINIO_ADDRESS=:9000
    command:
      - "server"
      - "/data"
    volumes:
      - ./minio-data:/data:Z


